### ISSUE TITLE
WorfFLow class has no contribute with function create_building_files()

### ISSUE THREAD

**Issue by Hammer-888** [NHERI-SimCenter/SimCenterBackendApplications#312]
as guide in [simcenter documents](https://nheri-simcenter.github.io/R2D-Documentation/common/developer_manual/examples/desktop/eqAssessment.html),applications\Workflow\R2DTool_workflow.py cannot running,may you update the docunment or update the repo Readme.
![image](https://github.com/user-attachments/assets/b93e68c9-9cfc-428f-88b6-0e1441bda149)

**Comment by fmckenna** [comment]
what version of R2D are you running and on what operating system are you running on?

**Comment by Hammer-888** [comment]
thanks for relpy, on window 10, i have success build the backend [1.2. Build the Backend Applications](https://nheri-simcenter.github.io/R2D-Documentation/common/developer_manual/how_to_build/desktop/how_to_build.html),and still have error as before.

**Comment by Hammer-888** [comment]
After build the backend , I just run the command,  as tht pic
![image](https://github.com/user-attachments/assets/ead2164b-0920-4690-a767-72b4540e1399)

**Comment by Hammer-888** [comment]
waiting for your help :)

**Comment by fmckenna** [comment]
I see what the problem is. 

We have just prepared a new major release of R2D (v5.0) and the backend has changed as a result.  The version now downloaded from DesignSafe is v5.0. The documentation is being finished before this release is announced and you have caught us in transition.

If you download the latest R2D and run an example locally you will find in your **~/Documents/R2D/LocalWorkdir/tmp.SimCenter** folder an input file, inputRWHALE.json, and an input_data folder. The folder and files represent the latest input files and formats for those files.

To run the workflow again from the command line, you can rename or move the **Results** folder that is in the **tmp.SimCenter** and run the following from a terminal.

**python**  <pathToBackendApplications>/applications/Workflow/rWhale.py   <pathToTmp.SimCenter/inputRWHALE.json --registry  <pathTpBackendApplications>/applications/Workflow/WorkflowApplications.json --referenceDir <pathToTmp.SimCenter>/input_data  -w <pathToTmp.SimCenter>/Results

**Comment by Hammer-888** [comment]
thank you very much, and do you have plan to update the documtens on the webpage[Run Locally on Your Desktop](https://nheri-simcenter.github.io/R2D-Documentation/common/developer_manual/architecture/desktop/run-manually/runLocal.html#lblrunlocal),thanks again

**Comment by fmckenna** [comment]
working on it as i type this.

**Comment by Hammer-888** [comment]
Hello me again, after your guidance, I can success running the R2D example1-E1BasicHAZUS.

But I got trouble in running R2D example3-E3PhysicsBasedGroundMotions.I can get the result with running R2D.exe, but with the same config input rWhale.py,I get bugs,may you give me some guidance again,thanks.
[log_rWhale.txt](https://github.com/user-attachments/files/16841920/log_rWhale.txt)
[log_R2Dexe.txt](https://github.com/user-attachments/files/16841923/log_R2Dexe.txt)

**Comment by Hammer-888** [comment]
tmp.SimCenter\Results\Buildings\1493\workdir.1 's result.out
`1.71847 3.37874 2.74876 4.6531 0.0219849 0.0354825 0.00610692 0.00985625 2.34734 4.26024 0.0343858 0.0664731 0.00360083 0.010291 0.00477581 0.00923237 `
rWhaleBackend Results\Buildings\2380\workdir.1 's reult.out
`0 0 0 0 0 0 `
